// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAIdEjw9B1mLF1ekuPJ41_LH6_WiOBnD00',
    appId: '1:396336759987:web:a787408815580552599cc6',
    messagingSenderId: '396336759987',
    projectId: 'stuntsync',
    authDomain: 'stuntsync.firebaseapp.com',
    storageBucket: 'stuntsync.appspot.com',
    measurementId: 'G-1H6D2963FL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB4a8Ibqw0os2l-tfI27OvKR-vDfijRGW0',
    appId: '1:396336759987:android:58cfc9751da4f320599cc6',
    messagingSenderId: '396336759987',
    projectId: 'stuntsync',
    storageBucket: 'stuntsync.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDIM8M4QW66yPByZfWcLKR36hcWx72_Ez8',
    appId: '1:396336759987:ios:5d8d61233e92bbca599cc6',
    messagingSenderId: '396336759987',
    projectId: 'stuntsync',
    storageBucket: 'stuntsync.appspot.com',
    androidClientId: '396336759987-6goutq33htahleuu1iv0gnk2t409n5p5.apps.googleusercontent.com',
    iosClientId: '396336759987-14cqk8u2tn1qae1v4ts2rbnc57hhka93.apps.googleusercontent.com',
    iosBundleId: 'com.stuntsync.stuntsync',
  );
}
